const mongoose=require("mongoose")
const ProSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        unique:true,
        min:2,
    },
    slug:{type:String, required:true, unique:true},
    category:[{
        type:mongoose.Types.ObjectId,
        ref:"category",
        default:null
    }],
    description:String,
    price:{
        type:Number,
        required:true,
        min:1
    },
    discount:{
        type:Number,
        min:0,
        default:0
    },
    afterDiscount:{
        type:Number,
        required:true,
        min:1

    },
    brand:{
        type:mongoose.Types.ObjectId,
        ref:"Brand",
        default:null,
    },
    tags:[String],
    atrributes:[{
        key:String,
        value:[String]
    }],
    seller:{
        type:mongoose.Types.ObjectId,
        ref:'User',
        default:null
    },
    image:[String],
    status:{
        type:String,
        enum:['active','inactive'],
        default:"inactive"
    },
    parentId:{
        type:mongoose.Types.ObjectId,
        ref:"Category",
        default:null
    },
    showInHome:{
        type:Boolean,
        default:false,
    },
    showInMenu:{
        type:Boolean,
        default:false,
    },
    createdBy:{
        type:mongoose.Types.ObjectId,
        ref:"User",
        default:null
    },
    updatedBy:{
        type:mongoose.Types.ObjectId,
        ref:"User",
        default:null
    }
},{
    timestamps:true,
    autoCreate:true,
    autoIndex:true,
})
const ProModel=mongoose.model("Product",ProSchema)
module.exports=ProModel